### Hae kaikki blogit
GET http://localhost:3003/api/blogs

### Lisää uusi blogi (käyttäjä lisätään automaattisesti backendissä)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testiblogi",
  "author": "Testaaja",
  "url": "http://example.com/testi",
  "likes": 5
}

### Luo uusi käyttäjä
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "matti123",
  "name": "Matti Meikäläinen",
  "password": "salasana"
}

### Hae kaikki käyttäjät
GET http://localhost:3003/api/users

### Kirjaudu sisään
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "jani123",
  "password": "salasana"
}
